# Generated by Django 2.0.5 on 2018-05-17 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('pers_nr', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='Personalnummer')),
                ('vor_name', models.CharField(max_length=30, verbose_name='Vorname')),
                ('nach_name', models.CharField(max_length=30, verbose_name='Nachname')),
                ('title_pre', models.CharField(max_length=10)),
                ('title_past', models.CharField(max_length=10)),
            ],
        ),
    ]
