# Generated by Django 2.0.4 on 2018-05-18 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zeit', '0002_auto_20180517_1935'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZeitKorrektur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art', models.CharField(choices=[('DI', 'Dienst'), ('SU', 'Sonderurlaub'), ('VB', 'Vergessene Buchung'), ('DR', 'Dienstreise')], max_length=2)),
                ('datum', models.DateField()),
                ('beginn', models.TimeField()),
                ('ende', models.TimeField()),
                ('begruendung', models.TextField(max_length=150, verbose_name='Begründung')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zeit.Person')),
            ],
        ),
    ]
